# Generated by Django 2.2 on 2020-01-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
